language: node_js
node_js:
- node
- '6'
addons:
  code_climate:
    repo_token: e343c2f43b67fdeaad91aa90c6010f2330d9440595c8337d7d757d0aa6cd25ae
notifications:
  slack:
    rooms:
      secure: ra5zxeEm6WrG+VeZwdx6ovpysk+gNpkvCTT+t5QP3QNt8GxeiD1Fonk3OrZwT7nmXb/vRCowWwXqJl7VSfyN1NMSiiL7Nal7/nDBijw2rXvfrpO71knZEpRIn3FfeRyRkYFfyAvYH38QygNHfOWHDG1u6Ybaq/+cDmFjYelM6N0O6PhB9vSc1exO9n522kyJVbDn9/I5yszWYQ8V2STPPPtPYwpLDtWJs3GRtSqoSJJGRJdySdshjOFkIPDHxtUAMialChp8bS1IohXMik/hZkxGP/ZgyoXQEZ95XE2ovjjahHd9amDUnn9Uod4joRI5jtQAsQOaLg+hcOetKvPgEVjbEXCWIx49cHcgsCGg2WHcaSXB5vWxsK02VBxBSfSEWB1/0ojVBDpagJzm88BBC9UZVUkudpYnPQjpGGYR1UjRJ/FL1PD7mAyIOKWj5Wb/m0lq784o44iGS4hNTpikrAPQ64Ha0o53H7Y7BUxQSQpX8A6J2v+J7ktrG0ugql/gxrbFpaALhbBdBUW7cDTPK36SNiPjzKGkOj2i7heI7zD8LkGgVr7IbBt5brLATtGD+EMNjNFZs/ttn0lQ4LQ+yWuwJyuk9jkR0Go02uSjFA+NrMRYj0STVS+fqpKhfJIWsZooC9yQ/ceolV1zlrGz0yWxbD2WzYHYKY9ue+d+F5Y=
  email: false
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
